apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- base/certificate.yaml
- base/configmap.yaml
- base/deployment.yaml
- base/ingress.yaml
- base/ingress-inline.yaml
- base/service.yaml
images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: b89fc603b7e842604dcbcd05e4f5c32beabceff7
