apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- base/certificate.yaml
- base/configmap.yaml
- base/deployment.yaml
- base/ingress.yaml
- base/service.yaml
images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: 37b15f1688ed4fbce8e8ab13b1d10ed993c15135
