apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- base/certificate.yaml
- base/configmap.yaml
- base/deployment.yaml
- base/ingress.yaml
- base/ingress-inline.yaml
- base/service.yaml
- base/service-account.yaml
- base/service-account-bindings.yaml
images:
- name: vatusa/cobalt
  newName: vatusa/cobalt
  newTag: ffceb80299196b902fc5b621a8baeb838ba8ccba
