global:
  security:
    allowInsecureImages: true
    
rabbitmq:
  image:
    registry: registry-1.docker.io
    repository: bitnamicharts/rabbitmq
    tag: 16.0.14

  auth:
    username: admin
    existingPasswordSecret: passwords
  primary:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m
