global:
  security:
    allowInsecureImages: true
    
rabbitmq:
  image:
    registry: registry-1.docker.io
    repository: bitnamicharts/rabbitmq
    digest: sha256:53769713d29cd8d9af4f1d3dfc9d02cc2fc9bd517c68bf65cefc6da99fb10f94

  auth:
    username: admin
    existingPasswordSecret: passwords
  primary:
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1000m
