apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cobalt-inline-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /web/$1
  labels:
    app: cobalt
spec:
  ingressClassName: nginx
  rules:
    - host: vatusa.net
      http:
        paths:
          - path: /cobalt/(.*)
            pathType: Exact
            backend:
              service:
                name: cobalt-service
                port:
                  number: 80
    - host: www.vatusa.net
      http:
        paths:
          - path: /cobalt/(.*)
            pathType: Exact
            backend:
              service:
                name: cobalt-service
                port:
                  number: 80
  tls:
    - hosts:
        - vatusa.net
        - www.vatusa.net
      secretName: cobalt-vatusa-net-tls