apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cobalt-inline-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /web
  labels:
    app: cobalt
spec:
  ingressClassName: nginx
  rules:
    - host: vatusa.net
      http:
        paths:
          - backend:
              service:
                name: cobalt-service
                port:
                  number: 80
            path: /cobalt
            pathType: Prefix
    - host: www.vatusa.net
      http:
        paths:
          - backend:
              service:
                name: cobalt-service
                port:
                  number: 80
            path: /cobalt
            pathType: Prefix
  tls:
    - hosts:
        - vatusa.net
        - www.vatusa.net
      secretName: cobalt-vatusa-net-tls